@startuml sequence_reference
actor ユーザ
boundary ログイン画面
boundary 他ユーザ一覧画面
control 他ユーザー情報取得
entity 他ユーザー

ユーザ -> ログイン画面 : ログインをクリック
ログイン画面 -> ユーザ : ログイン完了
ログイン画面 -> 他ユーザ一覧画面 : 画面遷移
他ユーザ一覧画面 -> 他ユーザー情報取得 : 他ユーザー情報の取得
他ユーザー情報取得 -> 他ユーザー : ユーザー情報参照
他ユーザー情報取得 -> 他ユーザ一覧画面 : ユーザー情報返却
他ユーザ一覧画面 -> ユーザ : ユーザー情報表示
@enduml
